// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// IsICANN provides a mock function for the type MockRegistry
func (_mock *MockRegistry) IsICANN(ctx context.Context, domain string) (bool, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for IsICANN")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistry_IsICANN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsICANN'
type MockRegistry_IsICANN_Call struct {
	*mock.Call
}

// IsICANN is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockRegistry_Expecter) IsICANN(ctx any, domain any) *MockRegistry_IsICANN_Call {
	return &MockRegistry_IsICANN_Call{Call: _e.mock.On("IsICANN", ctx, domain)}
}

func (_c *MockRegistry_IsICANN_Call) Run(run func(ctx context.Context, domain string)) *MockRegistry_IsICANN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistry_IsICANN_Call) Return(b bool, err error) *MockRegistry_IsICANN_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRegistry_IsICANN_Call) RunAndReturn(run func(ctx context.Context, domain string) (bool, error)) *MockRegistry_IsICANN_Call {
	_c.Call.Return(run)
	return _c
}

// IsICANNTld provides a mock function for the type MockRegistry
func (_mock *MockRegistry) IsICANNTld(ctx context.Context, tld string) (bool, error) {
	ret := _mock.Called(ctx, tld)

	if len(ret) == 0 {
		panic("no return value specified for IsICANNTld")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, tld)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, tld)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tld)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistry_IsICANNTld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsICANNTld'
type MockRegistry_IsICANNTld_Call struct {
	*mock.Call
}

// IsICANNTld is a helper method to define mock.On call
//   - ctx context.Context
//   - tld string
func (_e *MockRegistry_Expecter) IsICANNTld(ctx any, tld any) *MockRegistry_IsICANNTld_Call {
	return &MockRegistry_IsICANNTld_Call{Call: _e.mock.On("IsICANNTld", ctx, tld)}
}

func (_c *MockRegistry_IsICANNTld_Call) Run(run func(ctx context.Context, tld string)) *MockRegistry_IsICANNTld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistry_IsICANNTld_Call) Return(b bool, err error) *MockRegistry_IsICANNTld_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRegistry_IsICANNTld_Call) RunAndReturn(run func(ctx context.Context, tld string) (bool, error)) *MockRegistry_IsICANNTld_Call {
	_c.Call.Return(run)
	return _c
}

// LastUpdated provides a mock function for the type MockRegistry
func (_mock *MockRegistry) LastUpdated() (time.Time, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastUpdated")
	}

	var r0 time.Time
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (time.Time, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRegistry_LastUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastUpdated'
type MockRegistry_LastUpdated_Call struct {
	*mock.Call
}

// LastUpdated is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) LastUpdated() *MockRegistry_LastUpdated_Call {
	return &MockRegistry_LastUpdated_Call{Call: _e.mock.On("LastUpdated")}
}

func (_c *MockRegistry_LastUpdated_Call) Run(run func()) *MockRegistry_LastUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_LastUpdated_Call) Return(time1 time.Time, b bool) *MockRegistry_LastUpdated_Call {
	_c.Call.Return(time1, b)
	return _c
}

func (_c *MockRegistry_LastUpdated_Call) RunAndReturn(run func() (time.Time, bool)) *MockRegistry_LastUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Refresh(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistry_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockRegistry_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRegistry_Expecter) Refresh(ctx any) *MockRegistry_Refresh_Call {
	return &MockRegistry_Refresh_Call{Call: _e.mock.On("Refresh", ctx)}
}

func (_c *MockRegistry_Refresh_Call) Run(run func(ctx context.Context)) *MockRegistry_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_Refresh_Call) Return(err error) *MockRegistry_Refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_Refresh_Call) RunAndReturn(run func(ctx context.Context) error) *MockRegistry_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Source provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Source() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Source")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRegistry_Source_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Source'
type MockRegistry_Source_Call struct {
	*mock.Call
}

// Source is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) Source() *MockRegistry_Source_Call {
	return &MockRegistry_Source_Call{Call: _e.mock.On("Source")}
}

func (_c *MockRegistry_Source_Call) Run(run func()) *MockRegistry_Source_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_Source_Call) Return(s string) *MockRegistry_Source_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRegistry_Source_Call) RunAndReturn(run func() string) *MockRegistry_Source_Call {
	_c.Call.Return(run)
	return _c
}

// TLDs provides a mock function for the type MockRegistry
func (_mock *MockRegistry) TLDs(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TLDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistry_TLDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLDs'
type MockRegistry_TLDs_Call struct {
	*mock.Call
}

// TLDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRegistry_Expecter) TLDs(ctx any) *MockRegistry_TLDs_Call {
	return &MockRegistry_TLDs_Call{Call: _e.mock.On("TLDs", ctx)}
}

func (_c *MockRegistry_TLDs_Call) Run(run func(ctx context.Context)) *MockRegistry_TLDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_TLDs_Call) Return(strings []string, err error) *MockRegistry_TLDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRegistry_TLDs_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockRegistry_TLDs_Call {
	_c.Call.Return(run)
	return _c
}
